### ISSUE TITLE
Avoid building sand-houses

### ISSUE THREAD

**Issue by niansa** [AiTechEye/aliveai#1]

**Comment by niansa** [comment]
The AI should select house materials which do fall down if placed.

**Comment by niansa** [comment]
The AI should select house materials which do fall down if placed.

**Comment by AiTechEye** [comment]
only if it causing problems

**Comment by niansa** [comment]
It does.

**Comment by AiTechEye** [comment]
ok done https://github.com/AiTechEye/aliveai/commit/26706cc6429f156a4c28147c246d12c038c67e76

**Comment by niansa** [comment]
Wow this Issue with "wontfix" label has been fixed! Ty!
