### ISSUE TITLE
How do you use this? 

### ISSUE THREAD

**Issue by chris-roerig** [AiTechEye/aliveai#11]
I've installed the mods and set them to load. I've opened the aliveai in game menu but I have 0 bots. When/where do I issue the create_bot() commands?

**Comment by awz** [comment]
I'm also curious if others have this working with Minetest 5.2.    I'm new to Minetest and mods but I have installed https://content.minetest.net/packages/VanessaE/dreambuilder_modpack/

**Comment by AiTechEye** [comment]
a few months ago i also had this wierd problem, no bots was spawning at all, probably coused by mintest core abm (active block modifier) the bots are spawning in this way like the mosty other mobs mods

also other games/mods can affect, eg mods that are replacing default blocks (grass, stone, dirt) with blocks from the mod

did you enabled more then the "aliveai" mod in the modpack?
the "aliveai" mod in the modpack is the api, there is no bots in it

the create_bot(), should be named register_bot(), it is used to register bots to spawn in the game
