### ISSUE TITLE
forks and traders are floating

### ISSUE THREAD

**Issue by notavaliable** [AiTechEye/aliveai#12]
fork and traders NPCs are floating in my minetest 5.1.1 on GNU Linux
![image](https://user-images.githubusercontent.com/64876933/81129796-8d89f280-8f13-11ea-8f3c-7c8ef2dfb649.png)

**Comment by AiTechEye** [comment]
weird, cuz i made a model to avoid this, does it happens in mt 5.2 too?

**Comment by notavaliable** [comment]
![screenshot_20200528_021413](https://user-images.githubusercontent.com/64876933/83105671-161a2f80-a089-11ea-809a-30e4a6e7ac69.png)
in 5.1 the problem is a little different (there is only one npc)

**Comment by AiTechEye** [comment]
this one is flying
