### ISSUE TITLE
Runtime error, x is a nil value

### ISSUE THREAD

**Issue by Mathiaszero** [AiTechEye/aliveai#15]
AsyncErr: ServerThread::run Lua: Runtime error from mod '' in callback luaentity_Step(): ...5.3.0_dedicatedTest\bin\..\mods\aliveai\aliveai/base.lua:1569: attempt to perform arithmetic on field 'x' (a nil value)
stack traceback:
	...5.3.0_dedicatedTest\bin\..\mods\aliveai\aliveai/base.lua:1569: in function 'visiable'
	....3.0_dedicatedTest\bin\..\mods\aliveai\aliveai/event.lua:4: in function 'folowing'
	...-5.3.0_dedicatedTest\bin\..\mods\aliveai\aliveai/bot.lua:39: in function 'bot'
	...-5.3.0_dedicatedTest\bin\..\mods\aliveai\aliveai/bot.lua:16: in function <...-5.3.0_dedicatedTest\bin\..\mods\aliveai\aliveai/bot.lua:1>

The error happened right after I died when one of the NPCs used an acid attack. One possibility was that the NPC was trying to attack the dead player. I am using 5.3.0.

**Comment by AiTechEye** [comment]
fixed
