### ISSUE TITLE
Some houses are placed where the player is.

### ISSUE THREAD

**Issue by aleksejrs** [AiTechEye/aliveai#6]
Sometimes I am suddenly in the complete dark (blackness), and moving doesn't help. Actually, moving *more* does help: the problem is that a house has appeared where I am!

Minetest 5.0.1 (Debian's 5.0.1+repack-2~bpo10+1 or Flatpak from https://www.minetest.net/).

Threats and similar just deleted.

Other mods activated (I was trying to understand who is building the houses): basic_houses, dmobs, kpgmobs, mg_villages, mobf_trader, mobs_npc, dependencies from Debian).

**Comment by AiTechEye** [comment]
if its made by aliveai this is an extremely rare case ... nothing to do
