### ISSUE TITLE
Houses are partly suspended when the land is uneven

### ISSUE THREAD

**Issue by aleksejrs** [AiTechEye/aliveai#8]
![Minetest-houses-Screenshot_20190822_131837](https://user-images.githubusercontent.com/1025861/63507216-e9286300-c4df-11e9-9469-0aca2d3be093.png)

That often makes the doors unreachable (two meters above the ground).

**Comment by AiTechEye** [comment]
fixed: https://github.com/AiTechEye/aliveai/commit/029b5e513d3e8b33f405bc03c2e4661a6416a352
